language: julia
os:
  - linux
  - osx
  
julia:  
  - 1.0
  - 1.1
  - nightly  
matrix:
 allow_failures:
 - julia: nightly
 - julia: 1.1
 - os: osx
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(; coverage=true);'  
after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("CHCoordinateTransformations")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'